### ISSUE TITLE
"PayloadTooLargeError: request entity too large" when run "tronbox test"

### ISSUE THREAD

**Issue by dzarezenko** [tronprotocol/docker-tron-quickstart#44]
I am trying to run my unit tests with `tronbox test` command, but received this error:

```
Deploying contracts to development network...
ERROR: Request failed with status code 413
```

In the __Tron Quickstart__ console:
<img width="938" alt="Screen Shot 2019-04-11 at 14 39 00" src="https://user-images.githubusercontent.com/148570/55954540-9acca300-5c67-11e9-9509-f76bfa451b9c.png">

How can I fix this issue? Thanks!

**Comment by sullof** [comment]
That is not a problem with Tron Quickstart. The error is returned by JavaTron, i.e., it would be the same if you try to do the same request using Shasta or the Main Network.
I wonder why you need a so huge payload. BlockChain is done for small data, you should never send big data to it. 
Anyway, I am closing this issue because it is not an issue with Quickstart.

**Comment by dzarezenko** [comment]
@sullof , thank you for the answer. Why I need so huge payload? I have received a project from the other developer and I should implement unit tests for contracts from this project, that's all. When I started do that - I received this error. Will ask the same question in the __JavaTron__ repo.

Thank you one more time!
